## Techniques de transformation des données

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

Q1. Importer le fichier CSV contenant les données nettoyées.

In [ ]:
dataSet = pd.read_csv("network-traffic-mining\data\processed\dataset_reseau_clean.csv")

Q2. Afficher les 20 premières lignes du dataset afin d'avoir un aperçu de sa structure.

In [4]:
dataSet.head(20)

,machine_id,os_type,duree_connexion,nombre_requetes,volume_donnees,statut_connexion
0,M1381,Linux,124.841713,80,464.209300,success
1,M996,Linux,203.399243,212,696.590874,success
2,M1411,MacOS,71.099503,213,430.462099,success
3,M1448,Windows,150.118079,216,341.491727,fail
4,M1448,Android,182.837035,79,259.873768,success
5,M167,Android,143.479982,224,289.311325,success
6,M127,Windows,113.242452,198,312.953557,fail
7,M1247,Android,110.820160,168,679.286073,success
8,M1338,Windows,145.661309,234,424.517234,success
9,M162,MacOS,156.610195,258,601.261817,fail
10,M1279,Windows,162.468964,280,492.608417,success
11,M1005,MacOS,165.259168,116,694.718357,fail
12,M275,Android,160.669225,90,576.809142,fail
13,M398,Windows,147.515885,168,464.760631,fail
14,M1127,Android,174.387698,198,514.109032,fail
15,M346,Linux,120.775692,181,714.288534,success
16,M1470,Linux,96.678178,139,452.836608,fail
17,M1047,Linux,77.878234,138,602.025339,success
18,M1377,Linux,88.951119,142,356.112712,fail
19,M200,Linux,103.009415,241,497.154919,success

Q3. Afficher les statistiques descriptives des variables numériques afin d'observer les caractéristiques générales des données.

In [5]:
dataSet.describe()

       duree_connexion  nombre_requetes  volume_donnees
count     10000.000000      10000.00000    10000.000000
mean        120.074007        198.82050      499.935969
std          36.563021         59.30334      139.306894
min          18.026468         33.00000      112.902668
25%          96.162680        158.00000      408.091352
50%         120.775692        200.00000      502.638632
75%         144.170177        240.00000      589.425863
max         225.262332        364.00000      892.508398

Q4. Sélectionner les variables numériques du dataset afin de préparer leur transformation.

In [6]:
dataSet_numeric = dataSet.select_dtypes(include=['number'])

Q5. Appliquer une normalisation des variables numériques.

In [7]:
scaler = MinMaxScaler()
dataSet_numeric_scaled = pd.DataFrame(
    scaler.fit_transform(dataSet_numeric),
    columns=dataSet_numeric.columns
)

Q6. Créer une nouvelle variable appelée intensite_connexion représentant l'activité du trafic réseau, en combinant les variables nombre_requetes et volume_donnees.

In [8]:
dataSet['intensite_connexion'] = dataSet['nombre_requetes'] * dataSet['volume_donnees']
dataSet['intensite_connexion'].head()

0     37136.744008
1    147677.265379
2     91688.427089
3     73762.213040
4     20530.027695
Name: intensite_connexion, dtype: float64

Q7. Transformer la variable catégorielles explicative os_type en variables numérique afin de pouvoir les utiliser dans un modèle de machine learning.

In [9]:
dataSet = pd.get_dummies(dataSet, columns=['os_type'])
print(dataSet.head())

  machine_id  duree_connexion  nombre_requetes  volume_donnees  \
0      M1381       124.841713               80      464.209300
1       M996       203.399243              212      696.590874
2      M1411        71.099503              213      430.462099
3      M1448       150.118079              216      341.491727
4      M1448       182.837035               79      259.873768

  statut_connexion  intensite_connexion  os_type_Android  os_type_Linux  \
0          success         37136.744008            False           True
1          success        147677.265379            False           True
2          success         91688.427089            False          False
3             fail         73762.213040            False          False
4          success         20530.027695             True          False

   os_type_MacOS  os_type_Windows
0          False            False
1          False            False
2           True            False
3          False             True
4          False            False

Q8. Afficher la structure du dataset après transformation.

In [10]:
dataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   machine_id           10000 non-null  object
 1   duree_connexion      10000 non-null  float64
 2   nombre_requetes      10000 non-null  int64
 3   volume_donnees       10000 non-null  float64
 4   statut_connexion     10000 non-null  object
 5   intensite_connexion  10000 non-null  float64
 6   os_type_Android      10000 non-null  bool
 7   os_type_Linux        10000 non-null  bool
 8   os_type_MacOS        10000 non-null  bool
 9   os_type_Windows      10000 non-null  bool
dtypes: bool(4), float64(3), int64(1), object(2)
memory usage: 507.9+ KB

In [ ]:
dataSet.to_csv("network-traffic-mining\data\processed\dataset_reseau_transformed.csv", index=False)